// ============================================================================
// Export Validator — final gate before PDF/DOCX/DOC/TXT export
//
// Runs layout validation + fact validation + content checks.
// If any check fails, export is BLOCKED and the user is notified.
// ============================================================================

"use client";

import type { ResumeData } from "./types";
import { validateLayout } from "./layout-validator";
import { validateAgainstManifest, type FactManifest } from "./locked-facts";

export interface ExportValidationResult {
  canExport: boolean;
  layoutValid: boolean;
  factsValid: boolean;
  contentValid: boolean;
  errors: string[];
  warnings: string[];
  blockedReason: string | null;
}

/**
 * Validate a resume before export.
 * This is the FINAL gate — if any check fails, export is blocked.
 *
 * Checks:
 *   1. Layout: A4 page, char count, section presence, page utilization
 *   2. Facts: No hallucinated employers/education/certs/languages
 *   3. Content: No AI leaks, no placeholder text, no empty bullets
 */
export function validateForExport(
  resume: ResumeData,
  manifest?: FactManifest,
): ExportValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // === 1. LAYOUT VALIDATION ===
  const layout = validateLayout(resume);
  if (!layout.valid) {
    errors.push(...layout.issues);
  }

  // === 2. FACT VALIDATION (if manifest provided) ===
  let factsValid = true;
  if (manifest) {
    const factViolations = validateAgainstManifest(resume, manifest);
    if (factViolations.length > 0) {
      factsValid = false;
      errors.push(...factViolations);
    }
  }

  // === 3. CONTENT VALIDATION ===
  let contentValid = true;

  // Check for AI leak patterns
  const resumeText = JSON.stringify(resume).toLowerCase();
  const leakPatterns = [
    { pattern: /\bfrom jd\b/i, name: "from jd" },
    { pattern: /\bjob description\b/i, name: "job description" },
    { pattern: /\bats score\b/i, name: "ats score" },
    { pattern: /\bgenerated by ai\b/i, name: "generated by ai" },
    { pattern: /\boptimization summary\b/i, name: "optimization summary" },
    { pattern: /\bcandidate profile\b/i, name: "candidate profile" },
    { pattern: /\bkeywords added\b/i, name: "keywords added" },
  ];

  for (const { pattern, name } of leakPatterns) {
    if (pattern.test(resumeText)) {
      contentValid = false;
      errors.push(`AI leak detected: "${name}"`);
    }
  }

  // Check for placeholder text
  const placeholderPatterns = [
    /\[your name\]/i,
    /\[email\]/i,
    /\[phone\]/i,
    /\[company\]/i,
    /\[degree\]/i,
    /example university/i,
    /example company/i,
    /lorem ipsum/i,
  ];

  for (const pattern of placeholderPatterns) {
    if (pattern.test(resumeText)) {
      contentValid = false;
      errors.push(`Placeholder text detected: ${pattern.source}`);
    }
  }

  // Check for empty bullets
  for (const exp of resume.experience || []) {
    if (exp.bullets) {
      for (let i = 0; i < exp.bullets.length; i++) {
        if (!exp.bullets[i] || exp.bullets[i].trim().length < 10) {
          warnings.push(`Empty or very short bullet in ${exp.title} at ${exp.company} (bullet ${i + 1})`);
        }
      }
    }
  }

  // Check for double periods
  if (/\.{2,}/.test(resumeText)) {
    warnings.push("Double periods detected — should be single period");
  }

  const canExport = errors.length === 0;
  const blockedReason = canExport ? null : `Export blocked: ${errors.length} error(s) — ${errors.slice(0, 3).join("; ")}`;

  if (canExport) {
    console.info("[Export Validator] Resume is valid for export");
  } else {
    console.error(`[Export Validator] Export BLOCKED — ${errors.length} error(s):`, errors);
  }

  return {
    canExport,
    layoutValid: layout.valid,
    factsValid,
    contentValid,
    errors,
    warnings,
    blockedReason,
  };
}
