// ResumeAI Pro — mock/seed data for demo
import type {
  User, ResumeData, JobDescription, AIProvider, AIProviderLog, AIProviderSettings, PromptTemplate,
  BrandingConfig, FeatureFlags, AuditLog, CoverLetter, InterviewPackage, ATSReport,
} from "./types";
import { BRAND } from "./brand";

export const SEED_USER: User = {
  id: "u_demo_001",
  name: "Rachid El Sabah",
  email: "relsabah@gmail.com",
  avatarUrl: "",
  role: "super_admin", // exclusive to relsabah@gmail.com (see SUPER_ADMIN_EMAILS in brand.ts)
  provider: "email",
  createdAt: "2025-09-12T10:00:00Z",
  lastActiveAt: new Date().toISOString(),
  usage: { resumesGenerated: 14, atsChecks: 27, coverLetters: 9, interviewPreps: 6, downloads: 41 },
  status: "active",
};

export const SEED_RESUMES: ResumeData[] = [
  {
    id: "r_seed_001",
    name: "Alex Morgan",
    headline: "Senior Frontend Engineer",
    contact: {
      email: "alex.morgan@example.com",
      phone: "+1 (415) 555-0182",
      location: "San Francisco, CA",
      website: "alexmorgan.dev",
      linkedin: "linkedin.com/in/alexmorgan",
      github: "github.com/alexmorgan",
    },
    summary:
      "Senior Frontend Engineer with 7+ years building performant, accessible web applications at scale. Shipped products used by 40M+ monthly users. Specialized in React, TypeScript, and design systems. Reduced Largest Contentful Paint by 38% across 12 properties.",
    experience: [
      {
        id: "e1",
        company: "Vercel",
        title: "Senior Frontend Engineer",
        location: "Remote",
        startDate: "2022-03",
        endDate: "Present",
        bullets: [
          "Led migration of marketing site to Next.js App Router, cutting build times by 62% and improving Lighthouse scores from 71 to 98.",
          "Built design system used by 28 engineers across 6 teams; reduced UI bug rate by 41% over 12 months.",
          "Mentored 4 junior engineers; 3 promoted within a year.",
        ],
      },
      {
        id: "e2",
        company: "Airbnb",
        title: "Frontend Engineer",
        location: "San Francisco, CA",
        startDate: "2019-06",
        endDate: "2022-02",
        bullets: [
          "Implemented new search experience serving 40M monthly users; increased booking conversion by 6.4%.",
          "Owned accessibility audit and remediation for the host dashboard, achieving WCAG 2.1 AA compliance.",
        ],
      },
    ],
    education: [
      {
        id: "ed1",
        institution: "University of California, Berkeley",
        degree: "B.S.",
        field: "Computer Science",
        startDate: "2014-09",
        endDate: "2018-05",
        gpa: "3.8",
      },
    ],
    skills: [
      { id: "s1", name: "React", category: "Frontend", level: "expert" },
      { id: "s2", name: "TypeScript", category: "Languages", level: "expert" },
      { id: "s3", name: "Next.js", category: "Frontend", level: "expert" },
      { id: "s4", name: "Tailwind CSS", category: "Styling", level: "expert" },
      { id: "s5", name: "Node.js", category: "Backend", level: "advanced" },
      { id: "s6", name: "GraphQL", category: "API", level: "advanced" },
      { id: "s7", name: "Accessibility (WCAG)", category: "Quality", level: "advanced" },
      { id: "s8", name: "Performance Optimization", category: "Quality", level: "expert" },
    ],
    projects: [
      {
        id: "p1",
        name: "OpenResumeKit",
        description: "Open-source ATS-friendly resume component library.",
        url: "github.com/alexmorgan/openresumekit",
        bullets: ["1.4k GitHub stars", "Used by 200+ job seekers in beta"],
      },
    ],
    certifications: [
      { id: "c1", name: "AWS Certified Cloud Practitioner", issuer: "Amazon Web Services", date: "2023-08" },
    ],
    languages: [
      { id: "l1", name: "English", proficiency: "native" },
      { id: "l2", name: "Spanish", proficiency: "conversational" },
    ],
    achievements: ["Speaker — React Summit 2024", "Top 1% contributor — Vercel internal OSS"],
    template: "ats-professional",
    accentColor: "#1154A3",
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2025-12-04T14:30:00Z",
    source: "manual",
    fileName: "alex_morgan_resume.pdf",
  },
];

export const SEED_JDS: JobDescription[] = [
  {
    id: "jd_seed_001",
    title: "Senior Frontend Engineer",
    company: "Stripe",
    location: "Remote (US)",
    employmentType: "Full-time",
    salary: "$180,000 – $240,000",
    responsibilities: [
      "Build and maintain customer-facing UI used by millions of businesses.",
      "Collaborate with design and backend teams to ship reliable features.",
      "Drive performance and accessibility improvements across the dashboard.",
      "Mentor mid-level engineers and lead technical design reviews.",
    ],
    requiredSkills: ["React", "TypeScript", "JavaScript", "HTML", "CSS", "Accessibility", "Performance"],
    preferredSkills: ["Next.js", "GraphQL", "Node.js", "Testing", "Design Systems"],
    technologies: ["React", "TypeScript", "Next.js", "GraphQL", "Vite", "Playwright", "Storybook"],
    experienceYears: "5+ years",
    education: "B.S. in Computer Science or equivalent experience",
    keywords: ["React", "TypeScript", "accessibility", "performance", "design systems", "Next.js", "GraphQL", "WCAG", "frontend"],
    source: "text",
    createdAt: "2025-11-22T09:00:00Z",
  },
];

export const SEED_PROVIDERS: AIProvider[] = [
  {
    id: "p_puter",
    name: "Puter.js (Free, user-auth)",
    type: "puter",
    apiUrl: "https://api.puter.com",
    baseUrl: "https://api.puter.com",
    priority: 1,
    isActive: true,
    isDefault: true,
    isFallback: true,
    isBuiltIn: true,
    allowedForRegularUsers: true,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 2,
    rateLimitPerMinute: 60,
    applicationId: "resumeai-pro-app",
    clientId: "resumeai-pro-client",
    redirectUri: "https://resumeai.pro/auth/puter/callback",
    enabledModels: ["claude-sonnet-4", "gpt-4o", "gemini-2.0-flash", "llama-3.3-70b"],
    modelName: "claude-sonnet-4",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0,
    costPerOutputToken: 0,
    status: "healthy",
    usage: { requests: 1842, tokens: 940220, errors: 12, avgLatencyMs: 1820, cost: 0 },
    lastUsedAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
  },
  {
    id: "p_opencode",
    name: "OpenCode Zen (Free models)",
    type: "opencode",
    apiUrl: "https://opencode.ai/zen/v1",
    baseUrl: "https://opencode.ai/zen/v1",
    apiKey: "sk-5DCF8XXmP30pnE4xjEJvVnr9LikhJCxSKg8cR5iaCiMERiHGGuMlzfkvLAh0dPKa",
    priority: 2,
    isActive: true,
    isBuiltIn: true,
    allowedForRegularUsers: true,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 2,
    rateLimitPerMinute: 60,
    modelName: "deepseek-v4-flash-free",
    enabledModels: ["deepseek-v4-flash-free", "mimo-v2.5-free", "minimax-m3-free", "nemotron-3-ultra-free", "north-mini-code-free", "claude-sonnet-4", "gpt-5", "gemini-3-flash", "claude-opus-4-8", "gpt-5.5"],
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0,
    costPerOutputToken: 0,
    status: "healthy",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
  {
    id: "p_zai",
    name: "Z.ai Fallback (built-in)",
    type: "z-ai-fallback",
    apiUrl: "internal",
    baseUrl: "internal",
    priority: 99,
    isActive: true,
    isFallback: true,
    isBuiltIn: true,
    allowedForRegularUsers: true,
    timeout: 20000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 1,
    rateLimitPerMinute: 100,
    modelName: "glm-4.6",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0,
    costPerOutputToken: 0,
    status: "healthy",
    usage: { requests: 612, tokens: 281044, errors: 3, avgLatencyMs: 980, cost: 0 },
    lastUsedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  // === Super-admin-only providers (inactive by default — add API key to activate) ===
  {
    id: "p_openai",
    name: "OpenAI",
    type: "openai",
    apiUrl: "https://api.openai.com/v1",
    baseUrl: "https://api.openai.com/v1",
    priority: 10,
    isActive: false,
    isBuiltIn: false,
    allowedForRegularUsers: false,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 3,
    rateLimitPerMinute: 50,
    modelName: "gpt-4o-mini",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0.00000015,
    costPerOutputToken: 0.0000006,
    status: "untested",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
  {
    id: "p_anthropic",
    name: "Anthropic Claude",
    type: "claude",
    apiUrl: "https://api.anthropic.com/v1",
    baseUrl: "https://api.anthropic.com/v1",
    priority: 20,
    isActive: false,
    isBuiltIn: false,
    allowedForRegularUsers: false,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 3,
    rateLimitPerMinute: 40,
    modelName: "claude-3-5-sonnet-20241022",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "header",
    costPerInputToken: 0.000003,
    costPerOutputToken: 0.000015,
    status: "untested",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
  {
    id: "p_deepseek",
    name: "DeepSeek",
    type: "deepseek",
    apiUrl: "https://api.deepseek.com/v1",
    baseUrl: "https://api.deepseek.com/v1",
    priority: 15,
    isActive: false,
    isBuiltIn: false,
    allowedForRegularUsers: false,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 3,
    rateLimitPerMinute: 60,
    modelName: "deepseek-chat",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0.00000014,
    costPerOutputToken: 0.00000028,
    status: "untested",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
  {
    id: "p_groq",
    name: "Groq (fast inference)",
    type: "groq",
    apiUrl: "https://api.groq.com/openai/v1",
    baseUrl: "https://api.groq.com/openai/v1",
    priority: 12,
    isActive: false,
    isBuiltIn: false,
    allowedForRegularUsers: false,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 3,
    rateLimitPerMinute: 30,
    modelName: "llama-3.3-70b-versatile",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0,
    costPerOutputToken: 0,
    status: "untested",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
  {
    id: "p_openrouter",
    name: "OpenRouter (multi-model gateway)",
    type: "openrouter",
    apiUrl: "https://openrouter.ai/api/v1",
    baseUrl: "https://openrouter.ai/api/v1",
    priority: 25,
    isActive: false,
    isBuiltIn: false,
    allowedForRegularUsers: false,
    timeout: 30000,
    maxTokens: 4096,
    temperature: 0.7,
    retryAttempts: 3,
    rateLimitPerMinute: 20,
    modelName: "anthropic/claude-3.5-sonnet",
    streamingEnabled: true,
    supportsFunctionCalling: true,
    authType: "bearer",
    costPerInputToken: 0.000003,
    costPerOutputToken: 0.000015,
    status: "untested",
    usage: { requests: 0, tokens: 0, errors: 0, avgLatencyMs: 0, cost: 0 },
  },
];

export const SEED_PROVIDER_LOGS: AIProviderLog[] = [
  {
    id: "pl_1",
    providerId: "p_puter",
    providerName: "Puter.js (Free, user-auth)",
    requestType: "chat",
    modelName: "claude-sonnet-4",
    status: "success",
    latencyMs: 1842,
    inputTokens: 1240,
    outputTokens: 856,
    requestPreview: "Optimize this resume for ATS: Alex Morgan, Senior Frontend Engineer...",
    responsePreview: "Here is your optimized resume in InfoHAS Pro layout: {\"name\":\"Alex Morgan\"...",
    createdAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
  },
  {
    id: "pl_2",
    providerId: "p_puter",
    providerName: "Puter.js (Free, user-auth)",
    requestType: "chat",
    modelName: "claude-sonnet-4",
    status: "rate_limited",
    latencyMs: 120,
    errorMessage: "429 Too Many Requests — Puter free quota exceeded for this hour",
    requestPreview: "Generate cover letter for Stripe role...",
    createdAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
  },
  {
    id: "pl_3",
    providerId: "p_zai",
    providerName: "Z.ai Fallback (built-in)",
    requestType: "chat",
    modelName: "glm-4.6",
    status: "success",
    latencyMs: 980,
    inputTokens: 820,
    outputTokens: 412,
    requestPreview: "Generate cover letter for Stripe role (failover after Puter 429)...",
    responsePreview: "Dear Stripe Hiring Team, When I read about this Senior Frontend Engineer opportunity...",
    createdAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
  },
  {
    id: "pl_4",
    providerId: "p_puter",
    providerName: "Puter.js (Free, user-auth)",
    requestType: "test",
    modelName: "claude-sonnet-4",
    status: "success",
    latencyMs: 412,
    inputTokens: 12,
    outputTokens: 8,
    requestPreview: "Test prompt: say 'OK' if you can hear me.",
    responsePreview: "OK",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "pl_5",
    providerId: "p_zai",
    providerName: "Z.ai Fallback (built-in)",
    requestType: "chat",
    modelName: "glm-4.6",
    status: "error",
    latencyMs: 5023,
    errorMessage: "Network timeout (5s exceeded)",
    requestPreview: "Extract keywords from JD...",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];

export const SEED_PROVIDER_SETTINGS: AIProviderSettings = {
  defaultProviderId: "p_puter",
  defaultModel: "claude-sonnet-4",
  fallbackProviderIds: ["p_zai"],
  retryAttempts: 2,
  timeout: 30000,
  rateLimitPerMinute: 60,
  enableFailover: true,
  enableCaching: true,
  enableCostTracking: true,
};

export const SEED_PROMPTS: PromptTemplate[] = [
  {
    id: "pt_001",
    name: "ATS Resume Rewrite",
    category: "rewrite",
    content:
      "You are a senior ATS optimization expert. Rewrite the candidate's resume bullets to be ATS-friendly, quantified, and impactful. Keep all claims truthful. Use strong action verbs, add measurable outcomes where context permits, and embed target keywords naturally.\n\nTarget keywords: {{keywords}}\n\nOriginal resume:\n{{resume}}",
    version: 3,
    isActive: true,
    variables: ["keywords", "resume"],
  },
  {
    id: "pt_002",
    name: "Cover Letter — Modern",
    category: "cover-letter",
    content:
      "Write a modern, concise, ATS-friendly cover letter (~280 words) for {{role}} at {{company}}. Match the candidate's voice to the company's industry. Open with a specific, non-generic hook. Close with a confident CTA.\n\nCandidate resume:\n{{resume}}\n\nJob description:\n{{jd}}",
    version: 2,
    isActive: true,
    variables: ["role", "company", "resume", "jd"],
  },
  {
    id: "pt_003",
    name: "Interview Question Generator",
    category: "interview",
    content:
      "Generate a balanced interview preparation package for {{role}} at {{company}}. Include 3 technical, 3 behavioral, 2 situational, 2 HR, and 2 company-specific questions. For each, provide a recommended answer, 3-4 talking points, a STAR example, difficulty (easy/medium/hard), and 2 follow-up questions.\n\nCandidate resume:\n{{resume}}\n\nJob description:\n{{jd}}",
    version: 1,
    isActive: true,
    variables: ["role", "company", "resume", "jd"],
  },
  {
    id: "pt_004",
    name: "Aviation Cabin Crew ATS — 2,800-char One-Page",
    category: "ats",
    content:
      "ACT AS: Senior ATS Optimization Expert and Master Executive Resume Writer.\n\nOBJECTIVE: Optimise for maximum ATS score. Rewrite the resume to FILL EXACTLY ONE A4 PAGE (12pt font). Strategically weave in exact keywords, hard skills, and industry terminology to guarantee a 90%+ match rate.\n\nCONTEXT:\n- ATS SYSTEM: {{ats_system}} ({{ats_focus}})\n- INDUSTRY KEYWORDS: {{aviation_keywords}}\n- TONE: {{tone}}\n- FORMAT STYLE: {{format}}\n- STRATEGY: {{strictness}}\n\nINPUT DATA:\n[RESUME]: {{resume}}\n[JOB DESCRIPTION]: {{jd}}\n\nTASK 1: SCORING (Calculate ATS Score, Impact, Brevity, Keywords).\nTASK 2: REWRITE (STRICT PLAIN TEXT).\n\nCRITICAL LENGTH ENFORCEMENT (NON-NEGOTIABLE & STRICT):\nThe generated resume MUST contain EXACTLY 2,800 characters (excluding HTML tags). Not less, not more.\n- 2,100 characters is too short. DO NOT OUTPUT SHORT TEXT.\n- 3,000+ characters will cause page overflow. DO NOT EXCEED.\n- HOW TO HIT EXACTLY 2800 CHARACTERS INTELLIGENTLY:\n  1. If short: Expand content intelligently without filler. Add deep technical context. Improve impact-driven bullet points. Use 5-7 detailed bullets for the 2 most recent roles.\n  2. If too long: Summarize older roles (older than 5 years) to a single line. Keep summary to exactly 3 lines.\n\nFORMATTING RULES (NON-NEGOTIABLE):\n1. NO Emojis, Icons, Graphics, Colors, Tables, Columns, or Decorative Symbols.\n2. NO Underlines or horizontal rules (<hr>).\n3. FONT: Times New Roman, Size 12.\n\nSTRUCTURE:\n1. HEADER: Name (H1, Uppercase, Bold, LEFT ALIGNED), Contact Info (LEFT ALIGNED).\n2. SECTIONS (H3): PROFESSIONAL SUMMARY, EXPERIENCE, EDUCATION, SKILLS.\n3. EXPERIENCE ENTRIES: <h4><strong>Job Title</strong> | <strong>Company</strong>, Location | <strong>YYYY to YYYY</strong></h4>\n4. EDUCATION ENTRIES: <h4><strong>Degree</strong> | <strong>School</strong> | <strong>YYYY to YYYY</strong></h4>\n5. CONTENT: Use <strong> tags for bolding. NO markdown asterisks.\n\nRETURN JSON FORMAT ONLY:\n{\n  \"score\": number,\n  \"score_breakdown\": { \"impact\": number, \"brevity\": number, \"keywords\": number },\n  \"summary_critique\": \"string\",\n  \"missing_keywords\": [\"string\"],\n  \"matched_keywords\": [\"string\"],\n  \"optimized_content\": \"Valid HTML string...\"\n}",
    version: 1,
    isActive: true,
    variables: ["ats_system", "ats_focus", "aviation_keywords", "tone", "format", "strictness", "resume", "jd"],
  },
  {
    id: "pt_005",
    name: "Cabin Crew Keyword Injection",
    category: "keywords",
    content:
      "You are an aviation ATS keyword specialist. Analyze the candidate's resume and the target cabin crew job description. Identify which aviation keywords are missing and weave them naturally into the resume's experience and skills sections.\n\nAVIATION KEYWORD BANK:\n{{aviation_keywords}}\n\nCandidate resume:\n{{resume}}\n\nTarget job description:\n{{jd}}\n\nReturn JSON: { \"missing\": [\"keyword1\", ...], \"matched\": [\"keyword1\", ...], \"injection_suggestions\": [{ \"section\": \"experience\", \"entry\": \"Job Title at Company\", \"suggestion\": \"Rewritten bullet with keyword\" }] }",
    version: 1,
    isActive: true,
    variables: ["aviation_keywords", "resume", "jd"],
  },
];

export const SEED_BRANDING: BrandingConfig = {
  appName: BRAND.name,
  tagline: BRAND.tagline,
  primaryColor: BRAND.primaryColor,
  accentColor: BRAND.accentColor,
  logoUrl: BRAND.logoUrl,
  emailFromName: BRAND.name,
  emailFromAddress: BRAND.email,
  pdfFooterText: "Generated by ResumeAI Pro — resumeai.pro",
};

export const SEED_FLAGS: FeatureFlags = {
  enableResumeBuilder: true,
  enableATSChecker: true,
  enableOptimizer: true,
  enableCoverLetter: true,
  enableInterviewPrep: true,
  enableJDScraper: true,
  enableAIFailover: true,
  enableDonations: true,
  enableAds: false,
  maintenanceMode: false,
};

export const SEED_LOGS: AuditLog[] = [
  { id: "l1", timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(), actor: "alex.morgan@example.com", action: "ATS check completed", category: "resume", details: "Score 87/100 for resume r_seed_001", severity: "info" },
  { id: "l2", timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(), actor: "system", action: "AI provider failover", category: "ai", details: "Puter → Z.ai fallback (rate limit)", severity: "warning" },
  { id: "l3", timestamp: new Date(Date.now() - 1000 * 60 * 62).toISOString(), actor: "alex.morgan@example.com", action: "Cover letter exported (PDF)", category: "export", details: "cover_letter_stripe.pdf", severity: "info" },
  { id: "l4", timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), actor: "admin@resumeai.pro", action: "Prompt updated", category: "admin", details: "ATS Resume Rewrite v2 → v3", severity: "info" },
  { id: "l5", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), actor: "system", action: "Backup completed", category: "system", details: "R2 snapshot OK (128 MB)", severity: "info" },
];

export const SEED_COVER_LETTERS: CoverLetter[] = [
  {
    id: "cl_seed_001",
    title: "Cover Letter — Stripe",
    template: "modern",
    content:
      "Dear Stripe Hiring Team,\n\nWhen I read that Stripe's mission is to increase the GDP of the internet, two things came to mind: the team that ships the dashboard UI is the team that makes that promise tangible for millions of businesses, and that's exactly the team I want to join.\n\nOver the past seven years I've built and scaled React applications used by 40M+ monthly users — most recently leading Vercel's marketing migration to the App Router, cutting build times by 62% and lifting Lighthouse scores from 71 to 98. I've owned WCAG 2.1 AA remediation end-to-end and shipped the design system that now backs six internal teams.\n\nI'd love to bring that rigor to Stripe's dashboard. I'm available for a conversation any time and would welcome a technical screen.\n\nSincerely,\nAlex Morgan",
    resumeId: "r_seed_001",
    jdId: "jd_seed_001",
    company: "Stripe",
    role: "Senior Frontend Engineer",
    createdAt: "2025-11-22T11:00:00Z",
    updatedAt: "2025-11-22T11:20:00Z",
  },
];

export const SEED_INTERVIEW: InterviewPackage[] = [
  {
    id: "iv_seed_001",
    resumeId: "r_seed_001",
    jdId: "jd_seed_001",
    company: "Stripe",
    role: "Senior Frontend Engineer",
    createdAt: "2025-11-22T12:00:00Z",
    questions: [
      {
        id: "q1",
        category: "technical",
        question: "Walk me through how you'd optimize a React dashboard that takes 4s to become interactive.",
        difficulty: "medium",
        recommendedAnswer:
          "Profile first with React DevTools and Lighthouse. Common culprits: over-rendering list rows, large client bundles, and unoptimized images. I'd introduce React.memo / useMemo where referential equality matters, code-split routes, virtualize long lists, and move heavy work to web workers.",
        talkingPoints: ["Measure before optimizing", "Bundle splitting", "Virtualization", "Web workers", "Rerender audit"],
        starExample: {
          situation: "Vercel marketing site had a 71 Lighthouse score.",
          task: "Reach 95+ within a quarter.",
          action: "Migrated to App Router, code-split, introduced route-level suspense.",
          result: "Lighthouse hit 98; LCP dropped 38%.",
        },
        followUps: ["How would you measure success?", "What if the bottleneck were the network?"],
      },
      {
        id: "q2",
        category: "behavioral",
        question: "Tell me about a time you disagreed with a teammate on a technical decision.",
        difficulty: "easy",
        recommendedAnswer:
          "I prefer to disagree by building, not arguing. I'll prototype the alternative quickly, document the trade-offs in a one-pager, and let the team decide with data. This keeps relationships intact and surfaces the best decision.",
        talkingPoints: ["Prototype-first", "Documented trade-offs", "Data-driven decision", "Relationship preservation"],
        starExample: {
          situation: "Disagreed on CSS-in-JS vs Tailwind at Vercel.",
          task: "Pick the right styling system for the design system.",
          action: "Built a side-by-side benchmark, ran it past design.",
          result: "Team chose Tailwind; UI bug rate dropped 41%.",
        },
        followUps: ["What if you couldn't prototype?", "How do you handle stalemates?"],
      },
    ],
  },
];

export const SEED_ATS_REPORTS: ATSReport[] = [
  {
    id: "ats_seed_001",
    resumeId: "r_seed_001",
    scores: { ats: 87, formatting: 92, keywords: 78, content: 90, grammar: 95, completeness: 84 },
    recommendations: [
      { id: "rec1", severity: "warning", category: "Keywords", title: "Add 3 missing keywords", description: "Job description emphasizes WCAG, design systems, and Playwright — currently underrepresented.", fix: "Mention Playwright in test coverage and WCAG in your accessibility work explicitly." },
      { id: "rec2", severity: "info", category: "Formatting", title: "Contact phone format", description: "Phone uses parentheses which some ATS parsers dislike.", fix: "Use +1-415-555-0182 format." },
      { id: "rec3", severity: "success", category: "Content", title: "Strong quantified bullets", description: "62%, 41%, 98 Lighthouse — excellent measurable outcomes." },
    ],
    missingKeywords: ["Playwright", "Storybook", "Vite"],
    matchedKeywords: ["React", "TypeScript", "Next.js", "GraphQL", "Accessibility", "Performance"],
    weakSections: [],
    jdMatchPercent: 87,
    createdAt: "2025-12-01T10:00:00Z",
  },
];
