allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": true
  "core-js": true
  "ecc-universal": true
  "es5-ext": true
  "esbuild": true
  "msgpackr-extract": true
  "prisma": true
  "sharp": true
  "tesseract.js": true
  "unrs-resolver": true
  "workerd": true
