-- Migration 0012: ai_tasks.username backfill (historical fix, now a no-op)
--
-- HISTORY: this migration originally ran
--   ALTER TABLE ai_tasks ADD COLUMN username TEXT NOT NULL DEFAULT 'anonymous';
-- for databases that ran an older 0010_task_tracking.sql without the column.
-- 0010 was later amended to create `username` directly, so on every fresh
-- database the ALTER hit "duplicate column name: username" and BROKE the
-- migration chain (nothing after 0012 could apply).
--
-- ACTION: the ALTER is intentionally gone. Databases that needed it already
-- have it applied (recorded in d1_migrations). Fresh databases get the
-- column from 0010's CREATE TABLE. Nothing to do here anymore.
