// ============================================================================
// Build-time Plugin Registry Generator
// ============================================================================
// Cloudflare Workers cannot do filesystem globbing at runtime, so plugin
// discovery must happen at BUILD TIME. This script:
//
//   1. Scans /plugins/**/manifest.ts
//   2. Validates each manifest against the PluginManifest schema
//   3. Emits plugin-registry.generated.ts with static imports
//
// Core never imports individual plugins — only the generated registry.
//
// Usage:
//   npx tsx scripts/generate-plugin-registry.ts
//   npm run build  (integrated into build pipeline)
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';

// ── Configuration ──────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, '..');
const PLUGINS_DIR = path.join(ROOT, 'plugins');
const OUTPUT_DIR = path.join(ROOT, 'src', 'lib', 'plugin-sdk');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'plugin-registry.generated.ts');

interface RawPluginManifest {
  id: string;
  name: string;
  version: string;
  author: string;
  description: string;
  capabilities: string[];
  dependencies?: Array<{ id: string; versionRange: string }>;
  entry: string;
  configuration?: Record<string, unknown>;
  permissions?: string[];
}

// ── Schema Validation ───────────────────────────────────────────────────

const REQUIRED_FIELDS = ['id', 'name', 'version', 'author', 'description', 'capabilities', 'entry'] as const;
const VALID_ID_RE = /^[a-z][a-z0-9.-]+\.[a-z][a-z0-9.-]+$/;

function validateManifest(mf: RawPluginManifest, filePath: string): string[] {
  const errors: string[] = [];

  for (const field of REQUIRED_FIELDS) {
    if (!(field in mf) || mf[field] === undefined) {
      errors.push(`Missing required field: "${field}"`);
    }
  }

  if (mf.id && !VALID_ID_RE.test(mf.id)) {
    errors.push(`Invalid id "${mf.id}" — must match pattern: domain.name (e.g. "provider.anthropic-claude")`);
  }

  if (mf.version && !/^\d+\.\d+\.\d+/.test(mf.version)) {
    errors.push(`Invalid version "${mf.version}" — must be semver (e.g. "1.0.0")`);
  }

  if (mf.capabilities && !Array.isArray(mf.capabilities)) {
    errors.push('"capabilities" must be an array of strings');
  }

  if (mf.dependencies && !Array.isArray(mf.dependencies)) {
    errors.push('"dependencies" must be an array of { id, versionRange }');
  }

  if (mf.entry && !fs.existsSync(path.join(path.dirname(filePath), mf.entry))) {
    errors.push(`Entry file "${mf.entry}" not found relative to manifest`);
  }

  return errors;
}

// ── Discovery ──────────────────────────────────────────────────────────

function findManifests(): Array<{ filePath: string; manifest: RawPluginManifest }> {
  const results: Array<{ filePath: string; manifest: RawPluginManifest }> = [];

  if (!fs.existsSync(PLUGINS_DIR)) {
    console.log(`[plugin-registry] No plugins directory found at ${PLUGINS_DIR}`);
    return results;
  }

  const walk = (dir: string) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name === 'manifest.ts' || entry.name === 'manifest.js') {
        try {
          // eslint-disable-next-line @typescript-eslint/no-var-requires
          const manifest = require(fullPath) as RawPluginManifest;
          // Handle ES module exports (default export)
          const mf = (manifest as { default?: RawPluginManifest }).default ?? manifest;
          results.push({ filePath: fullPath, manifest: mf });
        } catch (err) {
          console.error(`[plugin-registry] ERROR loading manifest ${fullPath}:`, err);
        }
      }
    }
  };

  walk(PLUGINS_DIR);
  return results;
}

// ── Generate Registry File ─────────────────────────────────────────────

function generateRegistry(plugins: Array<{ filePath: string; manifest: RawPluginManifest }>): string {
  const lines: string[] = [
    '// ============================================================================',
    '// AUTO-GENERATED PLUGIN REGISTRY',
    '// Generated by scripts/generate-plugin-registry.ts',
    '// Do not edit manually — re-run `npm run build` to regenerate.',
    '// ============================================================================',
    '',
    'import type { PluginManifest } from \'./types\';',
    'import type { Plugin } from \'./interfaces/plugin\';',
    '',
  ];

  // Import each plugin's factory/create function
  // The entry field in the manifest points to the default export
  for (let i = 0; i < plugins.length; i++) {
    const { manifest } = plugins[i];
    const importName = `Plugin_${i}`;
    const relativePath = path.relative(OUTPUT_DIR, path.dirname(plugins[i].filePath));
    // Convert to forward-slash path for module resolution
    const modulePath = relativePath.replace(/\\/g, '/').replace(/\/manifest$/, '');
    const entryPath = manifest.entry.startsWith('./') ? manifest.entry.slice(2) : manifest.entry;

    lines.push(`import { create as ${importName} } from './${modulePath}/${entryPath.replace(/\.ts$/, '')}';`);
  }

  lines.push('');

  // Build the registry entry
  lines.push('// Each entry: [manifest, factory function]');
  lines.push('export const PLUGIN_REGISTRY: Array<[PluginManifest, () => Plugin]> = [');

  for (let i = 0; i < plugins.length; i++) {
    const { manifest } = plugins[i];
    const importName = `Plugin_${i}`;
    const deps = manifest.dependencies
      ? manifest.dependencies.map((d) => `{ id: '${d.id}', versionRange: '${d.versionRange}' }`).join(', ')
      : '';

    lines.push('  [{');
    lines.push(`    id: '${manifest.id}',`);
    lines.push(`    name: '${manifest.name}',`);
    lines.push(`    version: '${manifest.version}',`);
    lines.push(`    author: '${manifest.author}',`);
    lines.push(`    description: '${manifest.description}',`);
    lines.push(`    capabilities: [${manifest.capabilities.map((c: string) => `'${c}'`).join(', ')}],`);
    lines.push(`    dependencies: [${deps}],`);
    lines.push(`    entry: '${manifest.entry}',`);
    lines.push(`    configuration: ${JSON.stringify(manifest.configuration ?? {}, null, 6).split('\n').join('\n    ')},`);
    lines.push(`    permissions: [${(manifest.permissions ?? []).map((p: string) => `'${p}'`).join(', ')}],`);
    lines.push('  }, () => new PluginWrapper()],');
  }

  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────────────────

function main(): void {
  console.log('[plugin-registry] Scanning for plugin manifests...');
  const plugins = findManifests();

  if (plugins.length === 0) {
    console.log('[plugin-registry] WARNING: No plugin manifests found. Generating empty registry.');
    const emptyRegistry = [
      '// ============================================================================',
      '// AUTO-GENERATED PLUGIN REGISTRY (EMPTY)',
      '// Generated by scripts/generate-plugin-registry.ts',
      '// No plugins found — this is expected during initial development.',
      '// ============================================================================',
      '',
      'export const PLUGIN_REGISTRY: Array<never> = [];',
      '',
    ].join('\n');
    fs.writeFileSync(OUTPUT_FILE, emptyRegistry, 'utf-8');
    console.log(`[plugin-registry] Empty registry written to ${OUTPUT_FILE}`);
    return;
  }

  console.log(`[plugin-registry] Found ${plugins.length} plugin manifest(s):`);
  let totalErrors = 0;

  for (const { filePath, manifest } of plugins) {
    const errors = validateManifest(manifest, filePath);
    if (errors.length > 0) {
      totalErrors += errors.length;
      console.error(`\n  ❌ ${path.relative(ROOT, filePath)}:`);
      for (const err of errors) {
        console.error(`     - ${err}`);
      }
    } else {
      console.log(`  ✓ ${manifest.id} (${manifest.version})`);
    }
  }

  if (totalErrors > 0) {
    console.error(`\n[plugin-registry] FAILED: ${totalErrors} validation error(s) found.`);
    process.exit(1);
  }

  const registryContent = generateRegistry(plugins);
  fs.writeFileSync(OUTPUT_FILE, registryContent, 'utf-8');
  console.log(`\n[plugin-registry] Registry written to ${OUTPUT_FILE}`);
}

main();
